feature to filter out desired labels
JulesBelveze/bundler pull request #3
Opened 2022-09-29 10:36 UTC by IanMenendez

This feature aims to make it easier to get desired values from a  cluster

I got this idea since sometimes I wanted to select a big cluster of labels but only get the ones that where a minority

2022-09-29 10:47 UTC, JulesBelveze requested changes
Cool stuff! 
Could you make sure that the `MultiChoice` still works if the `color` column contains int? Also, `color` can be of type `float`. I don't know how this would behave in such case..

For example with `color` being an int I get the following issue:
```
ValueError: failed to validate MultiChoice(id='1058', ...).options: expected an element of List(Either(String, Tuple(String, String))), got seq with invalid items [0, 1, 2]
```

2022-09-29 11:20 UTC, IanMenendez commented
not the prettiest solution. 
I converted the color column to strings, as this is the type that MultiChoice accepts.
This works because when creating the new tab the only values that you use are the project id and the id of the label

2022-09-29 11:27 UTC, JulesBelveze requested changes

2022-09-29 11:27 UTC, JulesBelveze commented on bundler/text.py
> +
That's gonna be quite nasty if `color` is of type `float`.
I would either disable this feature in this case or use some sort of cursor (like [here](https://demo.bokeh.org/movies))

2022-10-03 07:39 UTC, JulesBelveze approved these changes

2022-10-03 07:40 UTC, JulesBelveze commented
@IanMenendez LGTM, I took the freedom to refactor a bit. Feel free to merge 😃

2022-10-03 08:05 UTC, IanMenendez commented
> @IanMenendez LGTM, I took the freedom to refactor a bit. Feel free to merge 😃

great! 
Can't merge because I don't have write access to  the repo  :sweat_smile:

2022-10-03 08:06 UTC, merged